version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env.docker
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
